# Starship config approximating existing Powerlevel10k theme.

add_newline = false

format = "$directory$git_branch$git_status "
right_format = "$status$cmd_duration$jobs"

[directory]
style = "fg:254 bg:238"
format = "[ $path$read_only ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false
home_symbol = "~"
read_only = " "
read_only_style = "fg:254 bg:238"

[git_branch]
symbol = " "
style = "fg:0 bg:7"
format = "[ $symbol$branch ]($style)"
truncation_length = 32
truncation_symbol = "…"

[git_status]
format = "${all_status}${ahead_behind}"
conflicted = "[ ~$count ](fg:1 bg:3)"
staged = "[ +$count](fg:0 bg:3)"
modified = "[ !$count](fg:0 bg:3)"
untracked = "[ ?$count ](fg:0 bg:3)"
stashed = "[ *$count ](fg:0 bg:3)"
ahead = "[ ⇡$count ](fg:0 bg:3)"
behind = "[ ⇣$count ](fg:0 bg:3)"
diverged = "[ ⇕⇡${ahead_count}⇣${behind_count} ](fg:0 bg:3)"
up_to_date = ""

[status]
disabled = false
format = "[ $symbol ]($style)"
success_symbol = "✔"
symbol = "✘"
map_symbol = true
pipestatus = true
success_style = "fg:2 bg:0"
failure_style = "fg:3 bg:1"

[cmd_duration]
min_time = 3000
format = "[ $duration ](fg:0 bg:3)"
show_milliseconds = false

[jobs]
format = "[ $symbol ](fg:6 bg:0)"
symbol = "✦"
